### ISSUE TITLE
Milestone 1 Planning and Discussion

### ISSUE THREAD

**Issue by vtaskaev1** [UBC-MDS/bccovideda#1]
**Tue Jan 11 2-4PM:** 
- Assigned main tasks per team member
- Assigned team member responsible for weekly milestone submission: (Milestone 1) Vanessa, (MS2) John, (MS3) Vadim, (MS4) Lianna
- Set next touchpoint meeting to Thu Jan 13 12:30PM

**Thu Jan 13 9AM:**
- Reviewed flow between functions 

**Fri Jan 14 7-8PM:**
- Discussed remaining milestone 1 tasks

**Milestone 1 Tasks:**
- [x] Creating Python package repo structure using _cookiecutter_ (Vanessa)
- [x] Amend Contributing, License, and ad-hoc repo structure files as needed (Vanessa)
- [x] Drafting Teamwork Contract, to be reviewed by everyone as needed (Lianna)
- [x] Draft repo README usage, including assessment of related research on relevant existing packages (Vadim)
- [x]  Draft function documentation: (1) getData, (2) showSummaryStat, (3) plotLineByDate, (4) plotHistByCond
- [x] GitHub Projects setup (Lianna)
- [x] Add main branch protection (Vadim)
- [x]  Finalize review of function docstrings, ensuring consistent convention (John)
- [x]  Remove any code from Milestone 1 submission (keep docstrings only)

**Comment by imtvwy** [comment]
Regarding the research on any existing similar packages, I have looked into a few in PyPI:
1. https://pypi.org/project/covid/
2. https://pypi.org/project/covid19pyclient/
3. https://github.com/PayneLab/covid19pandas
The first 2s provide some basic functions like getAllData, getDataByCountry.  The 3rd one does have a function to plot the rolling mean against a period of time.

To keep things simple, how about instead of having #4 a prediction modeling , maybe we can just provide function to get data by condition (date, range , a particular age group or sex?)

**Comment by imtvwy** [comment]
And after reviewing Milestone 1 checklist in details, I think each of us have to pick one function to work on the functional specification (for MS1), but not done by one person.  
Maybe we should decide the 4 functions here and confirm the name so that Vadim can easily refer in the README as well?
Some suggestions:
1. getAllData()
2. getDataByAgeGroup( ageGroup)
3. getDataBySex( M/F )
4. getDataByLocation( HA )
5. getDataByDate(StartDate, EndDate)
6. showSummaryStatistics()
7. plotNewCases(StartDate, EndDate)

**Comment by liannah** [comment]
I have also found this https://github.com/coa-project/pycoa/tree/main , as a similar package to ours. I believe there can be more similar packages, but I can find none for the BC data specifically. So I think we need to mention that in readme as our package will provide the plot and summary of the BC data. 

I think. what Vanessa suggested are pretty good options.

The first function can definitely be getData and then can be specified whether the data from cases or laboratory data. 
The second function can be plotting the cases by county, so we will show how many cases are in the specified county or in all counties if not specified. 
The third function can be ShowSummaryStatistics. 
The fourth function may be a histogram by age group of cases.

**Comment by vtaskaev1** [comment]
Fri Jan 14 7-8PM:

Some additional remaining tasks:
- [ ] Remove any code from Milestone 1 submission (keep docstrings only)
- [ ] Finalize docstring review

**Comment by liannah** [comment]
All tasks reviewed and ready to submit.
